"""仓储接口（Protocol）。SQLite 为当前实现，PostgreSQL 迁移时替换实现即可。"""
from __future__ import annotations

from typing import Protocol

from app.domain.enums import ReviewStatus
from app.domain.models import (
    Analysis,
    CollectionEvent,
    CollectionRequest,
    CollectionRun,
    Content,
    KbChunk,
    KbDocument,
    KbQaPair,
    RawAsset,
    Claim, Evidence, ReviewDecision, Report,
)


class RunRepository(Protocol):
    async def create(self, run: CollectionRun) -> None: ...

    async def get(self, run_id: str) -> CollectionRun | None: ...

    async def update(self, run: CollectionRun) -> None: ...

    async def list(self, limit: int = 50, offset: int = 0) -> list[CollectionRun]: ...


class CollectionRequestRepository(Protocol):
    async def create(self, req: CollectionRequest) -> None: ...

    async def get(self, request_id: str) -> CollectionRequest | None: ...

    async def update(self, req: CollectionRequest) -> None: ...

    async def list(
        self, limit: int = 50, offset: int = 0, status: str | None = None
    ) -> list[CollectionRequest]: ...


class EventRepository(Protocol):
    async def add(self, event: CollectionEvent) -> None: ...

    async def list_by_run(self, run_id: str) -> list[CollectionEvent]: ...


class ContentRepository(Protocol):
    async def upsert(self, content: Content) -> bool: ...

    async def update_content(self, content: Content) -> bool: ...

    async def get(
        self, content_id: str, app_visible_only: bool = False
    ) -> Content | None: ...

    async def list(
        self,
        limit: int = 50,
        offset: int = 0,
        platform: str | None = None,
        app_visible_only: bool = False,
        app_hidden: bool | None = None,
    ) -> list[Content]: ...

    async def search(
        self,
        query: str,
        exclude_content_id: str | None = None,
        limit: int = 20,
        app_visible_only: bool = False,
    ) -> list[Content]: ...

    async def update_review_status(self, content_id: str, status: ReviewStatus) -> bool: ...

    async def summary(self, limit: int = 20, app_visible_only: bool = False) -> list[dict]: ...

    async def set_app_hidden(self, content_id: str, hidden: bool) -> bool: ...

    async def delete_content(self, content_id: str) -> dict | None: ...


class RawAssetRepository(Protocol):
    async def add(self, asset: RawAsset) -> None: ...

    async def list_by_run(self, run_id: str) -> list[RawAsset]: ...


class ReviewRepository(Protocol):
    async def add_claim(self, claim: Claim) -> None: ...
    async def get_claim(self, claim_id: str, app_visible_only: bool = False) -> Claim | None: ...
    async def list_claims(self, content_id: str, batch_id: str | None = None) -> list[Claim]: ...
    async def list_review_batches(self, content_id: str) -> list[dict]: ...
    async def set_active_batch(self, content_id: str, batch_id: str) -> bool: ...
    async def save_review_batch(
        self,
        content_id: str,
        claims: list[Claim],
        evidences: list[Evidence],
        decisions: list[ReviewDecision],
        final_status: ReviewStatus,
        batch_id: str | None = None,
        replace: bool = False,
    ) -> str: ...
    async def update_claim(self, claim: Claim) -> None: ...
    async def add_evidence(self, evidence: Evidence) -> None: ...
    async def list_evidence(
        self, claim_id: str, app_visible_only: bool = False
    ) -> list[Evidence]: ...
    async def add_decision(self, decision: ReviewDecision) -> None: ...
    async def list_decisions(self, claim_id: str) -> list[ReviewDecision]: ...
    async def add_report(self, report: Report) -> None: ...
    async def get_report(self, report_id: str, app_visible_only: bool = False) -> Report | None: ...
    async def list_reports(
        self,
        limit: int = 50,
        offset: int = 0,
        content_id: str | None = None,
        app_visible_only: bool = False,
    ) -> list[Report]: ...


class AnalysisRepository(Protocol):
    async def add(self, analysis: Analysis) -> None: ...
    async def get(self, analysis_id: str, app_visible_only: bool = False) -> Analysis | None: ...
    async def list_by_content(
        self, content_id: str, limit: int = 50, offset: int = 0, app_visible_only: bool = False
    ) -> list[Analysis]: ...


class KnowledgeBaseRepository(Protocol):
    async def add_document(self, doc: KbDocument) -> None: ...
    async def get_document(
        self, doc_id: str, app_visible_only: bool = False
    ) -> KbDocument | None: ...
    async def get_document_by_source(self, source_type: str, source_id: str) -> KbDocument | None: ...
    async def get_document_by_hash(self, content_hash: str) -> KbDocument | None: ...
    async def list_documents(
        self, limit: int = 50, offset: int = 0, app_visible_only: bool = False
    ) -> list[KbDocument]: ...
    async def set_document_state(self, doc_id: str, status: str, chunk_count: int) -> None: ...
    async def add_chunks(self, chunks: list[KbChunk]) -> None: ...
    async def list_chunks_by_doc(self, doc_id: str) -> list[KbChunk]: ...
    async def iter_all_chunks(self) -> list[KbChunk]: ...
    async def iter_retrievable_chunks(self, app_visible_only: bool = False) -> list[KbChunk]: ...
    async def delete_chunks_by_doc(self, doc_id: str) -> None: ...
    async def update_document_body(
        self, doc_id: str, title: str, markdown: str, raw_text: str, content_hash: str
    ) -> None: ...
    async def delete_document(self, doc_id: str) -> None: ...
    # --- Q&A 知识条目（doc_type='qa'）---
    async def add_qa_pairs(self, pairs: list[KbQaPair]) -> None: ...
    async def get_qa_pair(self, qa_id: str) -> KbQaPair | None: ...
    async def list_qa_pairs(
        self, doc_id: str, app_visible_only: bool = False
    ) -> list[KbQaPair]: ...
    async def list_qa_pairs_by_status(
        self, status: str, limit: int = 50, offset: int = 0, app_visible_only: bool = False
    ) -> list[KbQaPair]: ...
    async def update_qa_pair(self, pair: KbQaPair) -> None: ...
    async def update_qa_pairs_status(self, qa_ids: list[str], status: str) -> int: ...
    async def delete_qa_pair(self, qa_id: str) -> None: ...
    async def delete_qa_pairs_by_doc(self, doc_id: str, status: str | None = None) -> int: ...
    async def count_qa_pairs_by_doc(
        self, doc_ids: list[str], status: str | None = None
    ) -> dict[str, int]: ...
    async def get_ready_source_ids(
        self, source_type: str, source_ids: list[str]
    ) -> set[str]: ...
